# TOML
# Definition of Rosary structures

[structure]
 [structure.basic]
 name = "Basic Rosary"
 preamble = [ "signofthecross", "apostlescreed", "ourfather", "hailmary", "hailmary", "hailmary", "glorybe" ]
 group = [ "announcegroup" ]
 mystery = [ "announcemystery", "ourfather", "hailmary", "hailmary", "hailmary", "hailmary", "hailmary", "hailmary", "hailmary", "hailmary", "hailmary", "hailmary", "glorybe" ]
 postamble = [ "hailholyqueen", "signofthecross" ]

 [structure.extended]
 name = "Extended Rosary"
 preamble = [ "signofthecross", "apostlescreed", "intentionsforrosary", "ourfather", "faith", "hailmary", "hope", "hailmary", "love", "hailmary", "glorybe" ]
 group = [ "announcegroup" ]
 mystery = [ "announcemystery", "ourfather", "hailmary", "hailmary", "hailmary", "hailmary", "hailmary", "hailmary", "hailmary", "hailmary", "hailmary", "hailmary", "glorybe" ]
 postamble = [ "hailholyqueen", "marianlitany", "letuspray", "stmichael", "signofthecross" ]


 [structure.fatima]
 name = "Extended Rosary with Fatima prayers"
 preamble = [ "queenoftheholyrosary", "signofthecross", "apostlescreed", "intentionsforrosary", "ourfather", "faith", "hailmary", "hope", "hailmary", "love", "hailmary", "glorybe", "ohmyjesus" ]
 group = [ "announcegroup" ]
 mystery = [ "announcemystery", "ourfather", "hailmary", "hailmary", "hailmary", "hailmary", "hailmary", "hailmary", "hailmary", "hailmary", "hailmary", "hailmary", "glorybe", "ohmyjesus", "fatimapardon" ]
 postamble = [ "hailholyqueen", "marianlitany", "letuspray", "stmichael", "signofthecross" ]

# Chaplet of Divine Mercy - use -groups five
 [structure.chapletofdivinemercy]
 name = "Chaplet of Divine Mercy"
 preamble = ["signofthecross", "youexpiredjesus", "ohfountoflife", "ohbloodandwater", "ohbloodandwater", "ohbloodandwater", "ourfather", "hailmary", "apostlescreed"]
 group = []
 mystery = ["eternalfather", 
	"sorrowfulpassion","sorrowfulpassion",
	"sorrowfulpassion","sorrowfulpassion",
	"sorrowfulpassion","sorrowfulpassion",
	"sorrowfulpassion","sorrowfulpassion",
	"sorrowfulpassion","sorrowfulpassion"]
 postamble = ["holyimmortalone", "holyimmortalone", "holyimmortalone", "eternalgod"]

# Chaplet of St. Michael - use -groups zero
 [structure.chapletofstmichael]
 name = "Chaplet of St. Michael"
 preamble = ["cometomyassistance","glorybe",
	"ourfather", "stmichaelchoirofseraphim",
	"hailmary", "hailmary", "hailmary",
	"ourfather", "stmichaelchoirofcherubim",
	"hailmary", "hailmary", "hailmary",
	"ourfather", "stmichaelchoirofthrones",
	"hailmary", "hailmary", "hailmary",
	"ourfather", "stmichaelchoirofdominions",
	"hailmary", "hailmary", "hailmary",
	"ourfather", "stmichaelchoirofpowers",
	"hailmary", "hailmary", "hailmary",
	"ourfather", "stmichaelchoirofvirtues",
	"hailmary", "hailmary", "hailmary",
	"ourfather", "stmichaelchoirofprincipalities",
	"hailmary", "hailmary", "hailmary",
	"ourfather", "stmichaelchoirofarchangels",
	"hailmary", "hailmary", "hailmary",
	"ourfather", "stmichaelchoirofangels",
	"hailmary", "hailmary", "hailmary",
	"ourfather", "ourfather", "ourfather", "ourfather",
 	"ohgloriousprince", "signofthecross"]
 group = []
 mystery = []
 postamble = []
